** 著者・所属機関名
*** No.1
発表者: yes
姓: 平手
名: 貴大
ふりがな姓: ひらて
ふりがな名: たかひろ
Given/First: Takahiro
Middle (任意):
Family/Last: Hirate
メールアドレス: hirate310@nagoya-u.jp
所属機関: 名古屋大学大学院

*** No.2
発表者: no
姓: 宋
名: 剛秀
ふりがな姓: そう
ふりがな名: たけひで
Given/First: Soh
Middle (任意): 
Family/Last: Takehide
メールアドレス: soh@lion.kobe-u.ac.jp
所属機関: 神戸大学 情報基盤センター

*** No.3
発表者: no
姓: 田村
名: 直之
ふりがな姓: たむら
ふりがな名: なおゆき
Given/First: Naoyuki
Middle (任意): 
Family/Last: Tamura
メールアドレス: tamura@kobe-u.ac.jp
所属機関: 神戸大学 情報基盤センター

*** No.4
発表者: no
姓: 番原
名: 睦則
ふりがな姓: ばんばら
ふりがな名: むつのり
Given/First: Mutsunori
Middle (任意): 
Family/Last: Banbara
メールアドレス: banbara@nagoya-u.jp
所属機関: 名古屋大学 大学院情報学研究科



** 講演情報
*** 発表希望テーマ
**** 第一希望
カテゴリ: オーガナイズドセッション
中分類: OS-8　AIと制約プログラミング
**** 第二希望 
カテゴリ: ???
中分類: ???

**** 発表言語: 日本語
*** キーワード
**** 1
キーワード(日): 解集合プログラミング
キーワード(英): Answer Set Programming
**** 2
キーワード(日): ハミルトン閉路問題
キーワード(英): Hamiltonian Cycle Problem
**** 3
キーワード(日): CEGAR
キーワード(英): Counterexample Guided Abstraction Refinement

**** 4
キーワード(日): 剰余数系
キーワード(英): Residue Number System
*** 発表方法
発表形式: 必須
口頭発表（現地）

*** 演題情報
以下のタイトルやアブストラクトの入力において、
濁点や半濁点を別文字として入力された場合、プロ
グラム冊子等の印刷物では文字間が間延びした表示
になる可能性があります。また、斜体やボールド体
、下線等の文字修飾は正しく印刷されないかもしれ
ません。
**** タイトル
日本語 必須: 
解集合プログラミングを用いたハミルトン閉路問題の解法に関する考察
English 必須: 
A Study on Solving Hamiltonian Cycle Problem with Answer Set Programming
**** サブタイトル
日本語: 
English: 
**** アブストラクト
目的と結果あるいは結論の概要を必ず記載してください。
必要に応じ方法の要点も記載してください。なお、論文
投稿時は、英文アブストラクトも入力が必須となります。

日本語 必須: 500文字以内で入力してください。
本研究では，解集合プログラミング(ASP)を用いて，大規模な
ハミルトン閉路問題およびその関連問題を効率よく解くソルバ
ーを実現することを目的としている．まず，ハミルトン閉路問
題を解く単純な ASP 符号化として，undirected, directed,
 acyclicity の3つを考案した．これらの符号化は，ハミルト
ン閉路問題を次数制約と連結制約の2つで簡潔に表現している．
次に，考案した符号化の有効性を評価するために，既存のベン
チマーク問題集を用いた実験を行った．その結果，directed
符号化がもっとも多くの問題を解きその有効性を示した．

さらに，連結制約を頂点ラベリングに基づく制約へと置き換えた
手法，RNSを用いた手法，CEGAR を用いた手法，その双方を用い
た手法を考案した．なお，単純な3符号化のいずれでも解けなかっ
た問題を用いた実験を行なったが，いずれでも新たに解けた問題
は存在しなかった．しかし，CEGAR を用いた２手法では，連結制
約を緩和しており，基礎化処理時間が短縮されるため，大規模な
問題への有効性が期待できる．

English: 
1200文字（約200語）以内


*** その他
**** 備考欄
